import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import JotaiProvider from "../atoms/JotaiProvider";
import { NextIntlClientProvider } from "next-intl";
import GlobalThemeProvider from "../provider/GlobalThemeProvider";
import { WEBSITE_NAME } from "../config";
import LoginPage from "../components/Login/LoginPage";
import { Stack } from "@mui/material";
import { PropsWithChildren } from "react";
import { getMessages } from "next-intl/server";

export const runtime = "edge";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: WEBSITE_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <Stack component="body" className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <AppRouterCacheProvider>
            <JotaiProvider>
              <GlobalThemeProvider>
                {children}
                <LoginPage />
              </GlobalThemeProvider>
            </JotaiProvider>
          </AppRouterCacheProvider>
        </NextIntlClientProvider>
      </Stack>
    </html>
  );
}
