import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import JotaiProvider from '../atoms/JotaiProvider'
import { NextIntlClientProvider, useMessages } from 'next-intl';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { locale } }: { children: React.ReactNode, params: { locale: string } }) {
  const messages = useMessages();


  return (
    <html lang={locale} >
      <body className={inter.className} >
        <NextIntlClientProvider messages={messages}>
          <AppRouterCacheProvider>
            <JotaiProvider>
              {children}
            </JotaiProvider>
          </AppRouterCacheProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
